#!/usr/bin/env bash
# _compose-settings.sh — shared Claude Code settings composition for apogee.
#
# This file is meant to be *sourced*, not executed. It defines the single
# canonical compose routine used by BOTH apogee-autonomous.sh (per-worktree)
# and apogee-sync-settings.sh (committed render), so the two can never drift.
#
#   source "$APOGEE_HOME/scripts/_compose-settings.sh"
#   apogee_compose_settings <baseline.json> <delta.json|""> <output> [banner]
#
# Composition rules:
#   - Recursive object merge: baseline * delta  (delta wins on scalar/object
#     conflicts; e.g. a product can override env or add new keys).
#   - Explicit UNION of the safety-critical permission arrays — allow, deny,
#     alwaysApproveReadonly, alwaysApproveTool, alwaysDenyTool — so a product
#     delta can only ADD to them, never silently drop a baseline entry.
#     This is the safety guarantee: the baseline deny list always survives.
#   - Optional banner injected as a top-level "//" key (JSON's comment idiom).
#
# Guarantees before writing output:
#   - baseline and delta (if given) are valid JSON
#   - composed result is valid JSON
#   - composed result has a NON-EMPTY deny list (else refuse)
#
# Returns 0 on success; non-zero with a message on stderr on failure.

# The banner stamped onto every generated settings.json. Kept here so the
# launcher and the sync command emit byte-identical output.
APOGEE_SETTINGS_BANNER="AUTO-GENERATED by apogee-sync-settings — DO NOT EDIT BY HAND. Edit .claude/settings.delta.json (your product additions only) and re-run apogee-sync-settings (or apogee-sync-all) to regenerate. Composed from apogee/.claude-shared/settings.json ⊔ this product's delta."

apogee_compose_settings() {
  local baseline="$1" delta="${2:-}" output="$3" banner="${4:-}"

  if [[ -z "$baseline" || ! -f "$baseline" ]]; then
    printf 'compose: baseline settings not found: %s\n' "$baseline" >&2
    return 1
  fi
  if ! jq empty "$baseline" 2>/dev/null; then
    printf 'compose: baseline is not valid JSON: %s\n' "$baseline" >&2
    return 1
  fi

  local have_delta=0
  if [[ -n "$delta" && -f "$delta" ]]; then
    if ! jq empty "$delta" 2>/dev/null; then
      printf 'compose: delta is not valid JSON: %s\n' "$delta" >&2
      return 1
    fi
    have_delta=1
  fi

  local tmp
  tmp="$(mktemp)"

  if [[ "$have_delta" -eq 1 ]]; then
    jq -s --arg banner "$banner" '
      .[0] as $base | .[1] as $delta
      | ($base * $delta)
      | .permissions.allow                 = (( ($base.permissions.allow                 // []) + ($delta.permissions.allow                 // [])) | unique)
      | .permissions.deny                  = (( ($base.permissions.deny                  // []) + ($delta.permissions.deny                  // [])) | unique)
      | .permissions.alwaysApproveReadonly = (( ($base.permissions.alwaysApproveReadonly // []) + ($delta.permissions.alwaysApproveReadonly // [])) | unique)
      | .permissions.alwaysApproveTool     = (( ($base.permissions.alwaysApproveTool     // []) + ($delta.permissions.alwaysApproveTool     // [])) | unique)
      | .permissions.alwaysDenyTool        = (( ($base.permissions.alwaysDenyTool        // []) + ($delta.permissions.alwaysDenyTool        // [])) | unique)
      | if $banner != "" then ({"//": $banner} + .) else . end
    ' "$baseline" "$delta" > "$tmp"
  else
    jq --arg banner "$banner" '
      if $banner != "" then ({"//": $banner} + .) else . end
    ' "$baseline" > "$tmp"
  fi

  if [[ $? -ne 0 ]] || ! jq empty "$tmp" 2>/dev/null; then
    rm -f "$tmp"
    printf 'compose: failed to produce valid JSON\n' >&2
    return 1
  fi

  local deny_count
  deny_count="$(jq '.permissions.deny | length' "$tmp" 2>/dev/null || echo 0)"
  if [[ "$deny_count" -le 0 ]]; then
    rm -f "$tmp"
    printf 'compose: refusing — composed deny list is empty (safety guarantee)\n' >&2
    return 1
  fi

  mkdir -p "$(dirname "$output")"
  mv "$tmp" "$output"
  return 0
}
